### PR TITLE
fix issue #29

### PR DESCRIPTION
**Pull request by mbaelde**
Replace all `.node` attributes to `.nodes` to work with `networkx>=2.0`.

### CODE REVIEW

**Comment by adamhadani** [comment]
LGTM - thanks @mbaelde !
FYI - I added one more change which is bumping the minimal version requirement of `networkx` to 2.0 to make sure people dont end up with older version installed and incompatible with this

**Comment by shan-96** [comment]
I am on networkx version 2.4 and still getting this error, which shouldn't be the case if this PR is merged

**Comment by mbaelde** [comment]
@shan-96 it is because the fix was merged on the `develop` branch not `master.

**Comment by shan-96** [comment]
Thanks. Any ETA on when it will be merged to master and released?

**Pull request merged**
